# Generated by Django 2.1.2 on 2018-10-25 05:35

from django.db import migrations, models
import post.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='posted on')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='post id')),
                ('photo', models.ImageField(upload_to=post.models.get_post_media_path)),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='posted on')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
