# Generated by Django 2.1.2 on 2018-10-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181022_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='posted on'),
        ),
    ]
