# Generated by Django 2.1.2 on 2018-10-22 04:20

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20181022_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=post.models.get_post_media_path),
        ),
    ]
